name: "Build V2"

on:
  push:
    branches: ["v2"]

defaults:
  run:
    shell: "bash"

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v6"
        with:
          persist-credentials: false

      - name: "Setup Go environment"
        uses: "actions/setup-go@v6"
        with:
          go-version: "1.26"

      - name: "Run tests"
        run: "make v2test"

      - name: "Build binaries"
        run: "make v2all"

      - name: "Setup env"
        run: |
          echo "timestamp=$(date '+%F-%H-%M-%S')" | tee -a "$GITHUB_ENV"

      - name: "Setup nFPM"
        env:
          GH_TOKEN: "${{ github.token }}"
        run: |
          gh release download --repo goreleaser/nfpm -p "*amd64.deb" -O nfpm.deb
          sudo apt-get install -y ./nfpm.deb

      - name: "Build packages"
        env:
          TIMESTAMP: "${{ env.timestamp }}"
        run: "nfpm package -f dist/v2/nfpm.yaml -p deb"

      - name: "Upload build artifacts"
        uses: "actions/upload-artifact@v4"
        with:
          name: "graylog-sidecar-${{ env.timestamp }}"
          path: "graylog-collector*"
